baseURL = "https://konakona.moe/"
title = "dw | konakona.moe"
defaultContentLanguage = "en"
copyright = "© 2022-2024 - konakona.moe - all rights reserved"
enableGitInfo = true
summaryLength = 35
enableRobotsTXT = true

[pagination]
	pagerSize = 8
	path = ""

[params]
  tracking = "<script defer src='https://u.konakona.moe/script.js' data-website-id='8d395101-a825-482a-8c56-b3988afc691f'></script>"
  keywords = ["linux", "blog", "autism", "foss", "open source", "github", "tutorials", "self-hosting", "personal", "hobby"]
  repository = "https://git.konakona.moe/dw/konakona.moe/commits/branch/master/"

[languages]
  [languages.en]
    LanguageName = "English"
    languageCode = 'en-GB'
    contentDir = 'content/en'
    weight = 10
      [[languages.en.menu.main]]
        name = 'home'
        url = '/'
        weight = 10
      [[languages.en.menu.main]]
        name = 'blog'
        url = '/blog/'
        weight = 20
      [[languages.en.menu.main]]
        name = 'about'
        url = '/about/'
        weight = 30
      [[languages.en.menu.main]]
        name = 'sign'
        url = '/sign/'
        weight = 30
      [[languages.en.menu.main]]
        name = 'git'
        url = 'https://git.konakona.moe/dw'
        weight = 50
        params.external = true


  [languages.fr]
    LanguageName = "Français"
    languageCode = 'fr-BE'
    contentDir = 'content/fr'
    weight = 20
      [[languages.fr.menu.main]]
        name = 'accueil'
        url = '/'
        weight = 10
      [[languages.fr.menu.main]]
        name = 'à propos'
        url = '/a-propos/'
        weight = 30
      [[languages.fr.menu.main]]
        name = 'git'
        url = 'https://git.konakona.moe/dw'
        weight = 40
        params.external = true

  [languages.pt]
    LanguageName = "Português"
    languageCode = 'pt-BR'
    contentDir = 'content/pt'
    weight = 30
      [[languages.pt.menu.main]]
        name = 'início'
        url = '/'
        weight = 10
      [[languages.pt.menu.main]]
        name = 'blog'
        url = '/blog/'
        weight = 20
      [[languages.pt.menu.main]]
        name = 'sobre'
        url = '/sobre/'
        weight = 30
      [[languages.pt.menu.main]]
        name = 'git'
        url = 'https://git.konakona.moe/dw'
        weight = 40
        params.external = true

    [params.buttons]
    [[params.buttons.button]]
      url = "https://www.konakona.moe"
      img = "konakona.png"
    [[params.buttons.button]]
      url = "https://nyaa.si/view/917375"
      img = "konata.gif"
    [[params.buttons.button]]
      url = "https://en.wikipedia.org/wiki/High-functioning_autism"
      img = "autism.png"
    [[params.buttons.button]]
      url = "https://gohugo.io/"
      img = "hugo.png"
    [[params.buttons.button]]
      url = "https://wiby.me"
      img = "wiby.gif"
    [[params.buttons.button]]
      url = "https://apple.com/"
      img = "macmade-fr.gif"
    [[params.buttons.button]]
      url = "https://windows.com/"
      img = "made-with-windows.gif"
    [[params.buttons.button]]
      url = "https://www.debian.org/"
      img = "debian-powered.gif"
    [[params.buttons.button]]
      url = "https://www.notepad.org/"
      img = "notepad-fulvio.gif"

[markup]
  [markup.highlight]
    codeFences = true
    style = "onedark"
    tabWidth = 4
    lineNumbersInTable = false
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      strikethrough = true
      table = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[taxonomies]
  # Disables all taxomies
