baseURL = "https://konakona.moe/"
defaultContentLanguage = "en"
copyright = "© 2022-2024 - konakona.moe - all rights reserved"
enableGitInfo = true
summaryLength = 35
enableRobotsTXT = true

[pagination]
	pagerSize = 8
	path = ""

[params]
  tracking = ""
  keywords = ["linux", "blog", "autism", "foss", "open source", "github", "tutorials", "self-hosting", "personal", "hobby"]
  repository = "https://github.com/dlol/website/commits/master/"

[languages]
  [languages.en]
    title = "diogo's website"
    LanguageName = "English"
    languageCode = 'en-GB'
    contentDir = 'content/en'
    weight = 10
      [[languages.en.menu.main]]
        name = 'home'
        url = '/'
        weight = 10
      [[languages.en.menu.main]]
        name = 'blog'
        url = '/blog/'
        weight = 20
      [[languages.en.menu.main]]
        name = 'about'
        url = '/about/'
        weight = 30
      [[languages.en.menu.main]]
        name = 'sign'
        url = '/guestbook/'
        weight = 40
      [[languages.en.menu.main]]
        name = 'git'
        url = 'https://github.com/dlol'
        weight = 50
        params.external = true

  [languages.fr]
    title = "site web à diogo"
    LanguageName = "Français"
    languageCode = 'fr-BE'
    contentDir = 'content/fr'
    weight = 20
      [[languages.fr.menu.main]]
        name = 'accueil'
        url = '/'
        weight = 10
      [[languages.fr.menu.main]]
        name = 'blog'
        url = '/blog/'
        weight = 20
      [[languages.fr.menu.main]]
        name = 'à propos'
        url = '/a-propos/'
        weight = 30
      [[languages.fr.menu.main]]
        name = 'signer'
        url = '/livre-d-or/'
        weight = 40
      [[languages.fr.menu.main]]
        name = 'git'
        url = 'https://github.com/dlol'
        weight = 50
        params.external = true

  [languages.pt]
    title = "site do diogo"
    LanguageName = "Português"
    languageCode = 'pt-BR'
    contentDir = 'content/pt'
    weight = 30
      [[languages.pt.menu.main]]
        name = 'início'
        url = '/'
        weight = 10
      [[languages.pt.menu.main]]
        name = 'blog'
        url = '/blog/'
        weight = 20
      [[languages.pt.menu.main]]
        name = 'sobre'
        url = '/sobre/'
        weight = 30
      [[languages.pt.menu.main]]
        name = 'ass.'
        url = '/livro-de-convidados/'
        weight = 40
      [[languages.pt.menu.main]]
        name = 'git'
        url = 'https://github.com/dlol'
        weight = 50
        params.external = true

    [params.buttons]
    [[params.buttons.button]]
      url = "https://en.wikipedia.org/wiki/High-functioning_autism"
      img = "autism.png"
    [[params.buttons.button]]
      url = "https://gohugo.io/"
      img = "hugo.png"
    [[params.buttons.button]]
      url = "https://wiby.me"
      img = "wiby.gif"
    [[params.buttons.button]]
      url = "https://apple.com/"
      img = "macmade-fr.gif"
    [[params.buttons.button]]
      url = "https://windows.com/"
      img = "made-with-windows.gif"
    [[params.buttons.button]]
      url = "https://www.debian.org/"
      img = "debian-powered.gif"
    [[params.buttons.button]]
      url = "https://www.notepad.org/"
      img = "notepad-fulvio.gif"

[markup]
  [markup.highlight]
    codeFences = true
    style = "onedark"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      strikethrough = true
      table = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[taxonomies]
  # Disables all taxomies
