baseURL = "https://konakona.moe/"
title = "SUPER KONAKONA"
paginatePath = ""
defaultContentLanguage = "en"
enableGitInfo = true
paginate = 15
summaryLength = 35
enableRobotsTXT = true

[params]
  tracking = "<script defer src='https://u.konakona.moe/script.js' data-website-id='8d395101-a825-482a-8c56-b3988afc691f'></script>"
  keywords = ["linux", "blog", "autism", "foss", "open source", "github", "tutorials", "self-hosting", "personal", "hobby"]

[languages]
  [languages.en]
    LanguageName = "English"
    languageCode = 'en-GB'
    contentDir = 'content/en'
    weight = 10

  [languages.fr]
    LanguageName = "Français"
    languageCode = 'fr-BE'
    contentDir = 'content/fr'
    weight = 20

  [languages.pt]
    LanguageName = "Português"
    languageCode = 'pt-BR'
    contentDir = 'content/pt'
    weight = 30

[markup]
  [markup.highlight]
    codeFences = true
    style = "onedark"
    tabWidth = 4
    lineNumbersInTable = false
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      strikethrough = true
      table = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[taxonomies]
  # Disables all taxomies
